// src/components/SynonymsList.tsx
import { useRef } from "preact/hooks";
import "../css/synonyms-list.css";
import { type SynonymGroup } from "../types/ResponseTypes";

export default function SynonymsList({
  success,
  word,
  synonymGroups,
}: {
  success: boolean;
  word: string;
  synonymGroups: SynonymGroup[];
}) {
  const containerRef = useRef<HTMLElement>(null);

  if (!success && synonymGroups.length === 0) {
    return (
      <section class="syn-list">
        <p class="syn-list__not-found">
          Nie znaleziono synonimów dla słowa <strong>"{word}"</strong>.
        </p>
      </section>
    );
  }

  function handleKeyDown(event: KeyboardEvent) {
    const cards = containerRef.current?.querySelectorAll<HTMLElement>(".syn-card");
    if (!cards?.length) return;

    const current = Array.from(cards).indexOf(
      document.activeElement as HTMLElement,
    );

    if (event.key === "ArrowRight") {
      event.preventDefault();
      cards[(current + 1) % cards.length].focus();
    }

    if (event.key === "ArrowLeft") {
      event.preventDefault();
      cards[(current - 1 + cards.length) % cards.length].focus();
    }
  }

  return (
    <section ref={containerRef} class="syn-list" onKeyDown={handleKeyDown}>
      <h2 class="syn-list__heading">
        Synonimy dla słowa <strong>{word}</strong>:
      </h2>
      {synonymGroups.map((group, index) => (
        <article tabIndex={0} class="syn-card" key={index}>
          <h3 class="syn-card__title">{group.group_meaning}</h3>
          <p class="syn-card__synonyms">
            {group.synonyms.join(", ")}
          </p>
        </article>
      ))}
    </section>
  );
}

// src/components/SynonymsList.vue
<template>
  <fieldset ref="containerRef" class="syn-list">
    <p class="syn-list__heading">
      Synonimy dla słowa <strong>{{ word }}</strong
      >:
    </p>
    <section v-if="!success && synonymGroups.length === 0" class="syn-list">
      <p class="syn-list__not-found">
        Nie znaleziono synonimów dla słowa <strong>"{{ word }}"</strong>.
      </p>
    </section>
    <article
      v-for="(group, index) in synonymGroups"
      v-else
      :key="index"
      tabindex="0"
      class="syn-card"
    >
      <h3 class="syn-card__title">{{ group.group_meaning }}</h3>
      <p class="syn-card__synonyms">{{ group.synonyms.join(", ") }}</p>
    </article>
  </fieldset>
</template>

<script setup lang="ts">
  import { onMounted, onUnmounted, ref } from "vue";
  import type { SynonymGroup } from "../types/ResponseTypes";
  import hotkeys from "hotkeys-js";

  defineProps<{
    success: boolean;
    word: string;
    synonymGroups: SynonymGroup[];
  }>();
  const containerRef = ref<HTMLElement | null>(null);

  function focusCard(index: number) {
    const cards = containerRef.value?.querySelectorAll<HTMLElement>(".syn-card");
    if (!cards?.length) return;

    const clamped = ((index % cards.length) + cards.length) % cards.length;
    cards[clamped].focus();
  }

  onMounted(() => {
    hotkeys("left,right", (event: KeyboardEvent) => {
      const active = document.activeElement;
      if (!active?.closest(".syn-list")) return;

      event.preventDefault();
      const cards = containerRef.value?.querySelectorAll<HTMLElement>(".syn-card");
      if (!cards?.length) return;

      const activeIndex = Array.from(cards).indexOf(active as HTMLElement);

      if (event.key === "ArrowRight" || event.key === "Right") {
        focusCard(activeIndex + 1);
      } else if (event.key === "ArrowLeft" || event.key === "Left") {
        focusCard(activeIndex - 1);
      }
    });
  });

  onUnmounted(() => {
    hotkeys.unbind("left,right");
  });
</script>

<style lang="css" scoped>
  .syn-list {
    margin-top: var(--size-6);
  }

  .syn-list__heading {
    font-size: var(--font-size-1);
    font-weight: 400;
    color: var(--text-2);
    margin-bottom: var(--size-3);
    margin-top: 0;
  }

  .syn-list__heading strong {
    color: var(--text-1);
  }

  .syn-list__not-found {
    font-size: var(--font-size-1);
    color: var(--text-2);
  }

  .syn-list__not-found strong {
    color: var(--text-1);
  }

  .syn-card {
    background: var(--surface-2);
    border: 1px solid var(--surface-4);
    border-radius: var(--radius-2);
    padding: var(--size-2) var(--size-4);
    margin-bottom: var(--size-2);
  }

  .syn-card:focus-visible {
    outline: 2px solid var(--brand);
    outline-offset: 2px;
  }

  .syn-card__title {
    font-size: var(--font-size-0);
    font-weight: var(--font-weight-7);
    text-transform: uppercase;
    letter-spacing: 0.04em;
    color: var(--text-2);
    margin: 0 0 var(--size-1) 0;
  }

  .syn-card__synonyms {
    font-size: var(--font-size-1);
    line-height: var(--font-lineheight-3);
    color: var(--brand);
    margin: 0;
  }
</style>
